// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TortenKreationSHS;

namespace TortenKreationSHS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20170904211005_Visit")]
    partial class Visit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("TortenKreationSHS.Models.Cake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<string>("TopImageUrl");

                    b.HasKey("Id");

                    b.ToTable("Cakes");
                });

            modelBuilder.Entity("TortenKreationSHS.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CakeId");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("CakeId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TortenKreationSHS.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ip");

                    b.Property<string>("UserAgent");

                    b.Property<DateTimeOffset>("VisitedAt");

                    b.HasKey("Id");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("TortenKreationSHS.Models.Image", b =>
                {
                    b.HasOne("TortenKreationSHS.Models.Cake")
                        .WithMany("Images")
                        .HasForeignKey("CakeId");
                });
#pragma warning restore 612, 618
        }
    }
}
